name:                hs
version:             0.1.0.0
github:              "githubuser/hs"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hs#readme>

dependencies:
- base >= 4.7 && < 5
- unordered-containers >= 0.2.14.0
- regex-posix >= 0.96.0.1
- array >= 0.5.4.0


library:
  source-dirs: src

executables:
  hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -O2
    - -funbox-strict-fields
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hs

tests:
  hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - hs
    - HUnit >= 1.6.1.0
